# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xerpE1KPR-f7Zsl5-uQTN3nlp5RDFDfT
"""



import streamlit as st
from nltk import ngrams
from nltk.tokenize import word_tokenize
nltk.download('punkt')


# Download NLTK data (if not already downloaded)
# Uncomment the line below if needed
# nltk.download('punkt')

# Function to generate n-grams
def generate_ngrams(text, n):
    tokens = word_tokenize(text)
    n_grams = list(ngrams(tokens, n))
    return n_grams

# Streamlit app
def main():
    st.title("N-gram Extractor")

    # User input
    text_input = st.text_area("Enter your text here:", "")

    # Select n-gram order
    n_gram_order = st.selectbox("Select n-gram order:", [2, 3, 4, 5])

    # Process and display n-grams
    if st.button("Generate N-grams"):
        if text_input:
            n_grams = generate_ngrams(text_input, n_gram_order)
            st.write(f"{n_gram_order}-grams:")
            st.write(n_grams)
        else:
            st.warning("Please enter some text.")

if __name__ == "__main__":
    main()
